# Generated by Django 3.2.8 on 2021-11-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matrix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='Batch',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='section',
            name='BoxNumber',
            field=models.IntegerField(default=21),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='ThreadCount',
            field=models.IntegerField(default='2'),
            preserve_default=False,
        ),
    ]
