# Generated by Django 3.2.8 on 2021-11-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matrix', '0002_auto_20211116_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='Color',
            field=models.CharField(default='blank', max_length=10),
            preserve_default=False,
        ),
    ]
