# Generated by Django 3.2.8 on 2021-11-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matrix', '0003_alter_section_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='BoxId',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='Color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
