# Generated by Django 3.2.8 on 2022-04-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matrix', '0004_auto_20211129_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPageModes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mode', models.CharField(default='light', max_length=10)),
            ],
        ),
    ]
