# Generated by Django 3.2.8 on 2022-04-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Matrix', '0007_rename_webpagemodes_webpagemode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpagemode',
            old_name='User',
            new_name='user',
        ),
    ]
